"""Publish stage: draft markdown + charts -> Notion page.

Usage:
    python -m stockstory.publish WORKDIR --quarter 2025-Q2 [--ticker AMZN]

Reads WORKDIR/draft.md (agent-authored markdown; chart positions marked as
`@@CHART:<slot>@@`), uploads WORKDIR/charts/*.png via single-part file uploads,
creates/updates `Tesis Individuales/<TICKER>/Stock-Story-{quarter}` and swaps
markers for image blocks.

Re-run semantics: same ticker+quarter replaces the page (old page trashed);
a different quarter creates a sibling.
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

from stockstory import notion

MARK = re.compile(r"@@CHART:([a-z_]+)@@")
MIME = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
        ".gif": "image/gif", ".webp": "image/webp"}

ROOT_TITLE = "tesis individuales"  # matched case/accent-insensitively


def _norm(s: str) -> str:
    import unicodedata
    return unicodedata.normalize("NFD", s).encode("ascii", "ignore").decode().lower().strip()


def find_root() -> str:
    d = notion.ntn_api(["v1/search", "-X", "POST"],
                       {"query": "Tesis Individuales",
                        "filter": {"property": "object", "value": "page"}})
    for r in d["results"]:
        try:
            t = r["properties"]["title"]
            title = (t.get("title") or [{}])[0].get("plain_text", "")
        except (KeyError, IndexError, AttributeError):
            continue
        if _norm(title) == ROOT_TITLE:
            return r["id"]
    raise notion.NtnError("Could not find the 'Tesis Individuales' root page. "
                          "Is it shared with the Notion integration?")


def ensure_child(parent_id: str, title: str) -> str:
    kids = notion.find_child_pages(parent_id)
    if _norm(title) in kids:
        return kids[_norm(title)]
    d = subprocess.run(["ntn", "pages", "create", "--parent", f"page:{parent_id}",
                        "--content", f"# {title}", "--json"],
                       capture_output=True, text=True)
    if d.returncode:
        raise notion.NtnError(f"page create failed: {d.stderr.strip()}")
    new_id = json.loads(d.stdout)["id"]
    notion.set_title(new_id, title)
    return new_id


def upload_image(path: Path) -> str:
    d = notion.ntn_api(["v1/file_uploads"], {
        "mode": "single_part", "filename": path.name,
        "content_type": MIME.get(path.suffix.lower(), "image/png")})
    notion.ntn_api([f"v1/file_uploads/{d['id']}/send", "--file", str(path)])
    return d["id"]


def insert_after(page_id: str, after_id: str, block: dict) -> str:
    d = notion.ntn_api([f"v1/blocks/{page_id}/children", "-X", "PATCH"],
                       {"children": [block],
                        "position": {"type": "after_block",
                                     "after_block": {"id": after_id}}})
    return d["results"][-1]["id"]


def page_children(page_id: str) -> list:
    out, cursor = [], None
    while True:
        args = [f"v1/blocks/{page_id}/children", "page_size==100"]
        if cursor:
            args.append(f"starting_cursor=={cursor}")
        d = notion.ntn_api(args)
        out += d["results"]
        if not d["has_more"]:
            return out
        cursor = d["next_cursor"]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("workdir")
    p.add_argument("--ticker", required=True)
    p.add_argument("--quarter", help="e.g. 2025-Q2; omitted -> page named 'draft'")
    args = p.parse_args()

    workdir = Path(args.workdir)
    draft = (workdir / "draft.md").read_text(encoding="utf-8")
    quarter = args.quarter or "draft"
    page_title = f"Stock-Story-{quarter}"

    print(notion.preflight())

    # upload charts referenced by markers
    slots = sorted(set(MARK.findall(draft)))
    uploads = {}
    for slot in slots:
        img = workdir / "charts" / f"{slot}.png"
        if img.exists():
            uploads[slot] = upload_image(img)
            print(f"uploaded {img.name}")
        else:
            draft = draft.replace(f"@@CHART:{slot}@@\n", "")
            print(f"chart {slot} missing -> marker dropped")

    # locate/create path, replace existing quarter page
    root = find_root()
    ticker_page = ensure_child(root, args.ticker)
    kids = notion.find_child_pages(ticker_page)
    if _norm(page_title) in kids:
        notion.ntn_api([f"v1/blocks/{kids[_norm(page_title)]}", "-X", "DELETE"])
        print(f"replaced existing {page_title}")
    page_id = ensure_child(ticker_page, page_title)

    # body with title (pages edit replaces ALL content, incl. the title H1),
    # draft callout, and markers as placeholder paragraphs
    body = (f"# {page_title}\n\n"
            "> ⚠️ DRAFT — generated by the stock-story pipeline. Review & edit.\n\n"
            + draft)
    body = MARK.sub(lambda m: f"CHARTPLACEHOLDER-{m.group(1)}", body)
    r = subprocess.run(["ntn", "pages", "edit", page_id],
                       input=body, capture_output=True, text=True)
    if r.returncode:
        raise notion.NtnError(f"page edit failed: {r.stderr.strip()}")
    notion.set_title(page_id, page_title)

    # swap placeholders for image blocks
    for block in page_children(page_id):
        if block["type"] != "paragraph":
            continue
        txt = "".join(x.get("plain_text", "")
                      for x in block["paragraph"].get("rich_text", []))
        m = re.fullmatch(r"CHARTPLACEHOLDER-([a-z_]+)", txt.strip())
        if not m or m.group(1) not in uploads:
            continue
        insert_after(page_id, block["id"], {
            "object": "block", "type": "image",
            "image": {"type": "file_upload",
                      "file_upload": {"id": uploads[m.group(1)]}}})
        notion.ntn_api([f"v1/blocks/{block['id']}", "-X", "DELETE"])
        print(f"placed chart {m.group(1)}")

    print(f"PAGE {page_id} https://app.notion.com/p/{page_title}-{page_id.replace('-', '')}")


if __name__ == "__main__":
    sys.exit(main())
